version: "3.8"

services:
  backup-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/zhyino/bnetdisk:latest
    container_name: backup-web
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data:rw
      - ./backup_log.txt:/app/backup_log.txt:rw
    restart: unless-stopped
    user: "1000:1001"
