version: "3.8"
services:
  backup-web:
    build: .
    image: ghcr.io/zhyino/bnetdisk:latest
    ports:
      - "18008:18008"
    volumes:
      - ./data:/app/data:rw
    environment:
      - BACKUP_DIR=/app/data
      - BACKUP_RATE=50
      - APP_PORT=18008
      - GUNICORN_WORKERS=2
      - GUNICORN_THREADS=4
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
