version: "3.8"
services:
  backup-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/zhyino/bnetdisk:latest
    container_name: backup-web
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:rw            # backup log and other data
      - /mnt/sda1/movies:/mnt/inputs:rw   # example host input mount, edit to your host paths
      - /mnt/sdb1/backups:/mnt/outputs:rw # example host output mount, edit to your host paths
    environment:
      - BACKUP_DIR=/app/data
      - ALLOWED_ROOTS=/mnt/inputs,/mnt/outputs,/app/data
    restart: unless-stopped
    user: "1000:1001"
