
version: "3.8"
services:
  backup-web:
    build: .
    image: ghcr.io/zhyino/bnetdisk:latest
    ports:
      - "18008:18008"
    volumes:
      - ./data:/app/data:rw
    environment:
      - BACKUP_DIR=/app/data
      - BACKUP_RATE=20
      - APP_PORT=18008
    restart: unless-stopped
