version: "3.8"

services:
  backup-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/zhyino/bnetdisk:latest
    container_name: backup-web
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data:rw
      - ./logs:/app/logs:rw  # 日志目录映射
      - /:/host:ro  # 只读挂载主机根目录，方便选择主机文件
    restart: unless-stopped
    user: "1000:1001"
    environment:
      - TZ=Asia/Shanghai
