name: Build and Push to GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录到GitHub Container Registry（GHCR）
      - name: Login to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}  # GitHub用户名
          password: ${{ secrets.GHCR_TOKEN }}      # 步骤1生成的PAT

      # 构建并推送镜像到GHCR
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          # GHCR镜像标签格式：ghcr.io/用户名/仓库名:标签
          tags: |
            ghcr.io/zhyino/bnetdisk:latest
            ghcr.io/zhyino/bnetdisk:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

